[phases.setup]
nixPkgs = ['php84', 'php84Extensions.mbstring', 'php84Extensions.pdo', 'php84Extensions.pdo_mysql', 'php84Extensions.tokenizer', 'php84Extensions.xml', 'php84Extensions.ctype', 'php84Extensions.json', 'php84Extensions.bcmath', 'php84Extensions.fileinfo']
